### ISSUE TITLE
get hard clear of costmaps as a new move_base recovery beaviour, instead of a general monitored nav recovery

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_movebase#28]
adding as a nav_core::RecoveryBehaviour: http://wiki.ros.org/nav_core?distro=indigo#RecoveryBehavior

**Comment by nilsbore** [comment]
The normal recovery behaviour should work, and it has previously. I'm guessing we just have to find the right option to enable it, it should take care of the voxel map too. To clear the whole map, we should just have to set the clearing radius parameter to 0.

I've previously implemented a recovery behaviour that clears the voxels closest to the robot and that worked back then: https://github.com/nilsbore/scitos_2d_navigation/tree/clear3d . Note that the code is practically the same as the `clear_costmap_recovery`.

**Comment by bfalacerda** [comment]
https://github.com/BFALacerda/strands_movebase/commit/83c13dd45d78be1253237df957d71e9180709d3a makes the monitored nav recovery behaviour redundant, so I'm closing this
