### ISSUE TITLE
No inflation layer on local costmap

### ISSUE THREAD

**Issue by cburbridge** [strands-project/strands_movebase#42]
There is no obstacle inflation in the local costmap because the inflation layer is commented out in https://github.com/strands-project/strands_movebase/blob/hydro-devel/strands_movebase/strands_movebase_params/local_costmap_params.yaml, is it supposed to be?

**Comment by nilsbore** [comment]
@BFALacerda changed this because the local planner does not take the
inflated cells into account anyways. It only cares about the occupied parts.

**Comment by bfalacerda** [comment]
i removed the inflation layer because dwa planner uses the robot footprint to check for collisions. If we also have the inflation layer, we're basically inflating twice. I kept it in the global costmap because the global plan is generated for a point robot

**Comment by hawesie** [comment]
My impression is that this leads to paths which are a little too close for comfort to obstacles, given the various sensor and localisation inaccuracies. Can we expand something to cause dwa to be a little safer?

**Comment by bfalacerda** [comment]
we can. it's a tradeoff between getting stuck more often and playing it more safe. the inflation layer can be enabled/disabled dynamically, so we might want to e.g. enable it when humans are around, but keep it disabled in tight areas?

**Comment by cdondrup** [comment]
Actually, we are currently looking at social costmaps for when humans are around: https://github.com/strands-project/strands_perception_people/issues/143 which should be a very low hanging fruit since the bayes tracker already produces the right output. This means we would not necessarily need the inflation. But being able to activate it dynamically would be nice because currently it is just commented which means we can't, right?

**Comment by bfalacerda** [comment]
yeah, we would have to put it back in and then have some node enabling/disabling it (or playing with the inflation radius and keeping it enabled all the time)

**Comment by cdondrup** [comment]
Would it be worth making the inflation radius part of the edge definition for topo nav to have the ability of changing it for certain parts of the environment? @Jailander @bfalacerda

**Comment by hawesie** [comment]
It's not just when humans are around. Chairs and tables have been problematic with our robots with no inflation. IMO we need a couple of centimetres of wiggle room to deal with noise from the sensors and localisation when encountering obstacles which are not in the map.

**Comment by Jailander** [comment]
I think we definitely need this capability and make it permanent. But, I don't know if adding the inflation radius to the topological map is the way to go, we can add this definition on the topological edges, I see how this would be useful like for example making sure the inflation radius is minimal on narrow edges and can be modified in wide spaces so for example defining if the inflation radius is dynamical and its min value for each edge.

my only fear is that the topological map definition is becoming somewhat hellish, what do you think @bfalacerda ?

**Comment by bfalacerda** [comment]
if there's a default value for all of these things so that in general we don't even need to think about them, that should be ok, so I'm for adding an extra field

**Comment by hawesie** [comment]
I'm not clear on the benefit of including the inflation in the edge. Most of our edges are the same wrt to inflation (IMO). The ones that aren't have special-purpose actions anyway. This also side-steps what the default should be: inflated a bit or not inflated.

**Comment by Jailander** [comment]
Yes, thinking about it @hawesie maybe its better if the actions themselves take care of this inflation, so I think it could be part of human aware navigation, door passing, etc ...
This way topological navigation only has to care about it setting it back to default fro cation that don't control the inflation radius such as move_base.

**Comment by Jailander** [comment]
@bfalacerda are we doing something else on the topological map level about it or do you think the inflation is enough?

**Comment by bfalacerda** [comment]
Not sure, I'm not completely satisfied or unsatisfied with either solution tbh. I'd be more inclined to have it in the top map definition, as the overhead of having it there is not too big I think... But we can also have a default that is only changed by certain nodes, or even as a recovery behaviour...

If you and @hawesie prefer not having it in the top map definition then be it

**Comment by bfalacerda** [comment]
we added a small inflation for the local costmaps. closing
