### ISSUE TITLE
remove_edges_laser not working in simulation

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_movebase#43]
it just gets core dumped when I try to run it. I tried it in 2 different computers and it happened in both. it doesnt happen in bob. Any idea @nilsbore ?

**Comment by nilsbore** [comment]
This could be due to one of the fields of the simulated message not being initialized properly. My bet would be on e.g. the intensity vector not being allocated in the incoming message. Don't have time to look into it today but maybe tomorrow morning.

**Comment by nilsbore** [comment]
I had a look now and the intensities vector is indeed zero in simulation. I'll just add a check to see if it's empty before copying but this should probably be fixed in strands_morse.

**Comment by bfalacerda** [comment]
thanks @nilsbore
