### ISSUE TITLE
hydro-devel vs indigo-devel

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_movebase#48]
We have been pushing changes to both branches lately, so they're out of sync.

https://github.com/strands-project/strands_movebase/pull/46 puts hydro-devel at a point where all nodes rin without crashing (there was an import error merged into it).

https://github.com/strands-project/strands_movebase/pull/47 gets indigo-devel up-to-date, and we should make it the default branch to avoid this in the future. @marc-hanheide I'm not sure how this version stuff works, is it ok to merge version increments from hydro-devel into indigo-devel?

**Comment by marc-hanheide** [comment]
yes, that pull requests look fine to me. What I noticed is that the release procedure for `strands-movebase` in https://github.com/strands-project-releases/strands_movebase/blob/master/tracks.yaml are set up to release from the default branch, i.e. currently `hydro-devel`. That's not good practice as the default might be changed by someone unnoticed to the system. So I suggest to tie the release track to `indigo-devel` after these have been merged and re-release?

**Comment by marc-hanheide** [comment]
actually doing it already ;-)

**Comment by marc-hanheide** [comment]
should be done and dusted. I suggest we make indigo-devel the new default branch here? Please confirm @bfalacerda @Jailander

**Comment by bfalacerda** [comment]
yes, please change default branch @marc-hanheide

**Comment by marc-hanheide** [comment]
done
